In [4]:
import torch
print(f"MPS 장치를 지원하도록 build가 되었는가? {torch.backends.mps.is_built()}")
print(f"MPS 장치가 사용 가능한가? {torch.backends.mps.is_available()}")

MPS 장치를 지원하도록 build가 되었는가? True
MPS 장치가 사용 가능한가? True


In [6]:
device = torch.device("mps")
torch.device('cuda' if (torch.cuda.is_available() and config['gpu'] != '-1') else 'cpu')

device(type='cpu')

In [13]:
c = torch.tensor([[ 1, 2, 3], [-1, 1, 4]] , dtype=torch.float)

In [15]:
c

tensor([[ 1.,  2.,  3.],
        [-1.,  1.,  4.]])

In [17]:
torch.norm(c, dim=1)

tensor([3.7417, 4.2426])

In [18]:
import numpy as np
np.sqrt((0.9041 + 2.1763)**2)

3.0804

In [19]:
import torch

a = torch.tensor([[ 0.9041,  0.0196],
                  [-0.3108, -2.4423],
                  [-0.4821,  1.0590]])

# 두 벡터 간의 유클리드 거리 계산
euclidean_distance = torch.norm(a[0] - a[1])

print(euclidean_distance)

tensor(2.7453)


In [72]:
import torch
from itertools import combinations

# 예시 입력 텐서
X = torch.tensor([[[ 0.9041,  0.0196,  1.5],
                   [-0.3108, -2.4423,  0.3],
                   [-0.4821,  1.0590, -0.8]],

                  [[ 0.9042,  0.0197,  1.7],
                   [-0.3108, -2.4423,  0.3],
                   [-0.4821,  1.0590, -0.8]]])

# Compute Euclidean distances for each feature pair
batch_size, seq_length, feat_dim = X.shape
num_combinations = feat_dim * (feat_dim - 1) // 2
pair_distances = torch.zeros((batch_size, seq_length, num_combinations), device=X.device)

# pair uclidean
comb_idx = 0
for (f1, f2) in combinations(range(feat_dim), 2):
    diff = X[:, :, f1] - X[:, :, f2]
    dist = diff.pow(2)
    pair_distances[:, :, comb_idx] = dist
    comb_idx += 1

# all uclidean 
all_distance = torch.sum(pair_distances, dim=2 ,keepdim=True)

a = torch.cat((pair_distances, all_distance), dim=-1) 

print(a)

tensor([[[ 0.7823,  0.3551,  2.1916,  3.3290],
         [ 4.5433,  0.3731,  7.5202, 12.4366],
         [ 2.3750,  0.1011,  3.4559,  5.9319]],

        [[ 0.7823,  0.6333,  2.8234,  4.2390],
         [ 4.5433,  0.3731,  7.5202, 12.4366],
         [ 2.3750,  0.1011,  3.4559,  5.9319]]])


In [73]:
a = [0.7823,  0.3551,  2.1916]
np.sum(a)

3.329

In [71]:
pair_distances

tensor([[[0.7823, 0.3551, 2.1916],
         [4.5433, 0.3731, 7.5202],
         [2.3750, 0.1011, 3.4559]],

        [[0.7823, 0.6333, 2.8234],
         [4.5433, 0.3731, 7.5202],
         [2.3750, 0.1011, 3.4559]]])

In [68]:
X = torch.tensor([[[ 0.9041,  0.0196,  1.5],
                   [-0.3108, -2.4423,  0.3],
                   [-0.4821,  1.0590, -0.8]],

                  [[ 0.9042,  0.0197,  1.7],
                   [-0.3108, -2.4423,  0.3],
                   [-0.4821,  1.0590, -0.8]]])

distances_2 = torch.sum(X, dim=2 ,keepdim=True)

print(distances_2)

tensor([[[ 2.4237],
         [-2.4531],
         [-0.2231]],

        [[ 2.6239],
         [-2.4531],
         [-0.2231]]])


In [66]:
sum([ -0.3108, -2.4423,  0.3])

-2.4531

In [ ]:
X = torch.tensor([[[ 0.9041,  0.0196,  1.5],
                   [-0.3108, -2.4423,  0.3],
                   [-0.4821,  1.0590, -0.8]],

                  [[ 0.9042,  0.0197,  1.7],
                   [-0.3108, -2.4423,  0.3],
                   [-0.4821,  1.0590, -0.8]]])


In [57]:
np.sqrt((0.9041-0.0196)**2 + (0.9041-1.5)**2 + (0.0196-1.5)**2)

1.824560555311881

In [ ]:
np.sqrt()

In [ ]:
distance.sum

In [32]:
np.sqrt((0.0196 - 1.5)**2)

1.4804

In [21]:
num_combinations

3

In [24]:
X.shape

torch.Size([2, 3, 3])

In [25]:
distances.shape

torch.Size([3, 2, 3])

In [74]:
import torch
import torch.nn as nn

In [83]:
import torch
import torch.nn as nn

class SleepEncoding(nn.Module):

    def __init__(self, sequence_length, sleep_feat_dim, d_model, dropout=0):
        super(SleepEncoding, self).__init__()
        self.sleep = nn.Parameter(torch.empty(sequence_length, sleep_feat_dim))  # 학습 가능한 파라미터
        self.d_model = d_model
        nn.init.uniform_(self.sleep, -0.02, 0.02)
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, x, sleep_feat):
        r"""Inputs of forward function
        Args:
            x: the sequence after positional encoding
            sleep_feat: additional feature tensor
        Shape:
            x: [sequence length, batch size, d_model]
            sleep_feat: [sequence length, batch size, feat_dim]
            output: [sequence length, batch size, d_model]
        """
        # Validate dimensions
        seq_len, batch_size, _ = x.size()
        assert sleep_feat.size(0) == seq_len and sleep_feat.size(1) == batch_size, \
            "Sequence length and batch size must match between x and sleep_feat"

        # Compute weighted sum of sleep features
        print("ㅎㅎ2:", self.sleep)
        weighted_sleep_feat = torch.einsum('sf,sbf->sb', self.sleep, sleep_feat)
        print("확인:\n",weighted_sleep_feat)

        # Expand to match the last dimension of x
        weighted_sleep_feat = weighted_sleep_feat.unsqueeze(-1).expand(-1, -1, self.d_model)
        print("확인2:\n",weighted_sleep_feat)
        print(weighted_sleep_feat.size)    

        # Add to x and apply dropout
        x = x + weighted_sleep_feat
        return self.dropout(x)

# Example usage
sequence_length = 4
sleep_feat_dim = 3
d_model = 512
dropout = 0.1

model = SleepEncoding(sequence_length, sleep_feat_dim, d_model, dropout)
x = torch.randn(sequence_length, 2, d_model)  # [sequence length, batch size, d_model]
sleep_feat = torch.tensor([[[1.0, 2.0, 3.0],
                            [4.0, 5.0, 6.0]],
                           [[7.0, 8.0, 9.0],
                            [10.0, 11.0, 12.0]],
                           [[13.0, 14.0, 15.0],
                            [16.0, 17.0, 18.0]],
                           [[19.0, 20.0, 21.0],
                            [22.0, 23.0, 24.0]]], requires_grad=True)  # [sequence length, batch size, feat_dim]

output = model(x, sleep_feat)
print(output.shape)  # Should be [sequence length, batch size, d_model]
print(output)


ㅎㅎ2: Parameter containing:
tensor([[ 0.0190, -0.0086, -0.0184],
        [-0.0045, -0.0015, -0.0058],
        [ 0.0018,  0.0126, -0.0121],
        [ 0.0137, -0.0157,  0.0180]], requires_grad=True)
확인:
 tensor([[-0.0533, -0.0773],
        [-0.0963, -0.1319],
        [ 0.0184,  0.0253],
        [ 0.3246,  0.3727]], grad_fn=<ViewBackward0>)
확인2:
 tensor([[[-0.0533, -0.0533, -0.0533,  ..., -0.0533, -0.0533, -0.0533],
         [-0.0773, -0.0773, -0.0773,  ..., -0.0773, -0.0773, -0.0773]],

        [[-0.0963, -0.0963, -0.0963,  ..., -0.0963, -0.0963, -0.0963],
         [-0.1319, -0.1319, -0.1319,  ..., -0.1319, -0.1319, -0.1319]],

        [[ 0.0184,  0.0184,  0.0184,  ...,  0.0184,  0.0184,  0.0184],
         [ 0.0253,  0.0253,  0.0253,  ...,  0.0253,  0.0253,  0.0253]],

        [[ 0.3246,  0.3246,  0.3246,  ...,  0.3246,  0.3246,  0.3246],
         [ 0.3727,  0.3727,  0.3727,  ...,  0.3727,  0.3727,  0.3727]]],
       grad_fn=<ExpandBackward0>)
<built-in method size of Tensor object at 0x1

In [ ]:
1.0, 2.0, 3.0

In [84]:
0.0190 +  2*(-0.0086) + 3*(-0.0184)

-0.0534

In [79]:
sleep_feat = torch.tensor([[[1.0, 2.0, 3.0],
                            [4.0, 5.0, 6.0]],
                           [[7.0, 8.0, 9.0],
                            [10.0, 11.0, 12.0]],
                           [[13.0, 14.0, 15.0],
                            [16.0, 17.0, 18.0]],
                           [[19.0, 20.0, 21.0],
                            [22.0, 23.0, 24.0]]], requires_grad=True)  # 

In [81]:
sleep_feat.size(-1)

3